In [1]:
import pandas as pd
df = pd.read_csv("C:/Users/34677/Documents/GitHub/Python para data science y big data esencial/base_datos_2008.csv")

In [2]:
df.groupby(by="DayOfWeek")["ArrDelay"].max()
# cambiando la función al final podemos obtener la información que necesitemos
# quizá la función más interesante es describe

DayOfWeek
1    1583.0
2    1951.0
3    1510.0
4    2453.0
5    1707.0
6    1525.0
7    2461.0
Name: ArrDelay, dtype: float64

In [3]:
df.groupby(by="DayOfWeek")["ArrDelay"].min()

DayOfWeek
1   -519.0
2    -89.0
3    -87.0
4   -129.0
5    -86.0
6    -91.0
7    -92.0
Name: ArrDelay, dtype: float64

In [4]:
df.groupby(by="DayOfWeek")["ArrDelay"].mean()

DayOfWeek
1     8.210850
2     7.481208
3     6.522017
4     8.411599
5    10.953440
6     5.789666
7     9.495886
Name: ArrDelay, dtype: float64

In [5]:
df.groupby(by="DayOfWeek")["ArrDelay"].describe()

               count       mean        std    min   25%  50%   75%     max
DayOfWeek
1          1013410.0   8.210850  38.013811 -519.0 -10.0 -2.0  12.0  1583.0
2          1005992.0   7.481208  38.361073  -89.0 -11.0 -3.0  11.0  1951.0
3          1016995.0   6.522017  36.024679  -87.0 -10.0 -3.0  10.0  1510.0
4          1011970.0   8.411599  37.397411 -129.0 -10.0 -1.0  12.0  2453.0
5          1008872.0  10.953440  40.252320  -86.0  -9.0  0.0  15.0  1707.0
6           841663.0   5.789666  37.163120  -91.0 -11.0 -3.0   9.0  1525.0
7           956127.0   9.495886  41.759296  -92.0 -10.0 -2.0  12.0  2461.0

In [6]:
df.groupby(by="DayOfWeek")["ArrDelay"].count()

DayOfWeek
1    1013410
2    1005992
3    1016995
4    1011970
5    1008872
6     841663
7     956127
Name: ArrDelay, dtype: int64

In [7]:
df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].describe()
# se puede comparar una lista de columnas agrupadas

C:\Users\34677\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

            ArrDelay                                                        \
               count       mean        std    min   25%  50%   75%     max
DayOfWeek
1          1013410.0   8.210850  38.013811 -519.0 -10.0 -2.0  12.0  1583.0
2          1005992.0   7.481208  38.361073  -89.0 -11.0 -3.0  11.0  1951.0
3          1016995.0   6.522017  36.024679  -87.0 -10.0 -3.0  10.0  1510.0
4          1011970.0   8.411599  37.397411 -129.0 -10.0 -1.0  12.0  2453.0
5          1008872.0  10.953440  40.252320  -86.0  -9.0  0.0  15.0  1707.0
6           841663.0   5.789666  37.163120  -91.0 -11.0 -3.0   9.0  1525.0
7           956127.0   9.495886  41.759296  -92.0 -10.0 -2.0  12.0  2461.0

            DepDelay
               count       mean        std    min  25%  50%   75%     max
DayOfWeek
1          1015833.0  10.269990  35.231766 -534.0 -4.0 -1.0   8.0  1552.0
2          1009095.0   8.976897  34.651637  -61.0 -5.0 -1.0   6.0  1952.0
3          1019685.0   8.289761  32.816088  -71.0 -5.0 -1.0   6.0  1518.0
4          1014470.0   9.772897  34.151512  -61.0 -4.0 -1.0   8.0  2467.0
5          1011381.0  12.158036  37.202673  -92.0 -4.0  0.0  11.0  1710.0
6           844112.0   8.645681  33.959105  -79.0 -5.0 -1.0   7.0  1521.0
7           958906.0  11.568973  38.624609  -67.0 -4.0 -1.0   9.0  2457.0

In [9]:
df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].mean()

C:\Users\34677\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

            ArrDelay   DepDelay
DayOfWeek
1           8.210850  10.269990
2           7.481208   8.976897
3           6.522017   8.289761
4           8.411599   9.772897
5          10.953440  12.158036
6           5.789666   8.645681
7           9.495886  11.568973

In [10]:
df.groupby(by="DayOfWeek")["ArrDelay"].max()-df.groupby(by="DayOfWeek")["ArrDelay"].min()
# podemos realizar operaciones con nuestros objetos 'groupby'.

DayOfWeek
1    2102.0
2    2040.0
3    1597.0
4    2582.0
5    1793.0
6    1616.0
7    2553.0
Name: ArrDelay, dtype: float64

In [15]:
# Para realizar el siguiente tipo de análisis, que es un poco más complejo, vamos a crear una 
#nueva base de datos, que la llamaremos 'dfATLHOU'
dfATLHOU = df[df.Origin.isin(["ATL","HOU"])]

In [16]:
dfATLHOU.groupby(by = ["DayOfWeek","Origin"])["ArrDelay"].mean()
# se comparan varias columnas agrupadas

DayOfWeek  Origin
1          ATL        9.123436
           HOU        6.356856
2          ATL        8.933587
           HOU        9.348112
3          ATL        8.809146
           HOU        9.073109
4          ATL       10.186501
           HOU       12.994016
5          ATL       14.797440
           HOU       11.036545
6          ATL        9.511662
           HOU        4.283933
7          ATL       13.798627
           HOU        7.045287
Name: ArrDelay, dtype: float64

In [17]:
dfATLHOU.groupby(by = ["Origin","DayOfWeek"])["ArrDelay"].mean()
# el orden de la agrupación es importante

Origin  DayOfWeek
ATL     1             9.123436
        2             8.933587
        3             8.809146
        4            10.186501
        5            14.797440
        6             9.511662
        7            13.798627
HOU     1             6.356856
        2             9.348112
        3             9.073109
        4            12.994016
        5            11.036545
        6             4.283933
        7             7.045287
Name: ArrDelay, dtype: float64

In [18]:
mygroupby=dfATLHOU.groupby(by = ["Origin","DayOfWeek"])["ArrDelay"]
# los objetos 'groupby' pueden guardarse

In [19]:
mygroupby.mean()

Origin  DayOfWeek
ATL     1             9.123436
        2             8.933587
        3             8.809146
        4            10.186501
        5            14.797440
        6             9.511662
        7            13.798627
HOU     1             6.356856
        2             9.348112
        3             9.073109
        4            12.994016
        5            11.036545
        6             4.283933
        7             7.045287
Name: ArrDelay, dtype: float64

In [20]:
mygroupby.describe()

                    count       mean        std   min   25%  50%   75%     max
Origin DayOfWeek
ATL    1          60598.0   9.123436  30.958642 -69.0  -8.0  1.0  14.0   407.0
       2          59732.0   8.933587  34.750658 -89.0  -9.0 -1.0  13.0   848.0
       3          60245.0   8.809146  34.343042 -56.0  -9.0  0.0  13.0   876.0
       4          59721.0  10.186501  35.261512 -51.0  -8.0  1.0  15.0   571.0
       5          60007.0  14.797440  38.859778 -51.0  -7.0  3.0  20.0   699.0
       6          49734.0   9.511662  36.020584 -61.0 -10.0 -1.0  15.0   483.0
       7          57664.0  13.798627  42.466233 -86.0  -8.0  1.0  17.0   612.0
HOU    1           8205.0   6.356856  28.887113 -47.0  -7.0 -2.0   9.0   383.0
       2           8368.0   9.348112  35.321852 -44.0  -7.0 -1.0  12.0   546.0
       3           8330.0   9.073109  33.191673 -39.0  -7.0 -1.0  12.0   639.0
       4           8188.0  12.994016  39.360946 -42.0  -6.0  1.0  17.0  1082.0
       5           8209.0  11.036545  32.415069 -48.0  -6.0  1.0  16.0   560.0
       6           5614.0   4.283933  32.518381 -47.0  -9.0 -3.0   6.0   917.0
       7           7331.0   7.045287  30.820505 -55.0  -7.0 -1.0  11.0   685.0

In [21]:
mygroupby.std()

Origin  DayOfWeek
ATL     1            30.958642
        2            34.750658
        3            34.343042
        4            35.261512
        5            38.859778
        6            36.020584
        7            42.466233
HOU     1            28.887113
        2            35.321852
        3            33.191673
        4            39.360946
        5            32.415069
        6            32.518381
        7            30.820505
Name: ArrDelay, dtype: float64